# version: '3.8'
# services:
#   backend:
#     env_file:
#       - .env
#     build:
#       context: ./backend
#       dockerfile: Dockerfile

#   frontend:
#     depends_on:
#       - backend
#     build:
#       context: .
#       dockerfile: Dockerfile
    